spring:
  datasource:
    url: jdbc:postgresql://postgres_accounts:5432/accounts?currentSchema=accounts&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: postgres

accounts:
  msg: "Welcome to the EazyBank Accounts Prod Application"
  buildVersion: 1
  mailDetails:
    hostName: "prod-accounts@eazybank.com"
    port: 9010
    from: "prod-accounts@eazybank.com"
    subject: "Your Account Details from EazyBank Prod Environment"
  activeBranches:
    - Hyderabad
    - Paris
    - "New York"
