spring:
  datasource:
    url: jdbc:postgresql://postgres-loans:5432/loans?currentSchema=loans&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: postgres

loans:
  msg: 'Welcome to the EazyBank Loans Default Application'
  buildVersion: 3
  mailDetails:
    hostName: 'default-loans@eazybank.com'
    port: 9001
    from: 'default-loans@eazybank.com'
    subject: 'Your Loan Details from EazyBank Default Environment'
  activeBranches:
    - Mumbai
    - London
    - Washington
